-- Günün sözü havuzunu genişletir. Tekrar çalıştırmak güvenlidir.

insert into public.quotes (body, author) values
  ('Bir şeye başlamanın en iyi zamanı dündü, ikinci en iyi zamanı bugün.', null),
  ('Küçük işler büyük işlerin provasıdır; sıkılmadan yapan kazanır.', null),
  ('Yapamadıklarını değil, yapabileceğin tek şeyi düşün.', null),
  ('Acele etme; ama durma.', 'Goethe'),
  ('İnsan ancak cesaret ettiği kadar büyür.', null),
  ('Bilmediğini bilmek, bilmenin başlangıcıdır.', 'Sokrates'),
  ('Hayat, sen planlar yaparken başına gelenlerdir.', 'John Lennon'),
  ('Düşen bir kez, kalkan bin kez öğrenir.', null),
  ('Kendine iyi davran; bu maratonda tek koşucu sensin.', null),
  ('Zihnin dağınıksa masanı topla, sonra tekrar bak.', null),
  ('En zor kısım oturmaktır; gerisi kendiliğinden gelir.', null),
  ('Rüzgârı değiştiremezsin ama yelkeni ayarlayabilirsin.', null),
  ('Bugünün işini yarına bırakma; yarının kendi işi var.', null),
  ('Sabır, acı bir bitkidir ama meyvesi tatlıdır.', null),
  ('İyi bir soru, iyi bir cevaptan değerlidir.', null),
  ('Bir işi seviyorsan, zorluğu da seversin.', null),
  ('Yavaş git, ama geri gitme.', null),
  ('Hata yapmayan, yeni bir şey denemiyordur.', 'Einstein'),
  ('Dünkü halinden iyiysen, kazandın demektir.', null),
  ('Yorgunluk geçer, pişmanlık kalır.', null),
  ('Aklına gelen her fikri yazmazsan, aklın yeni fikir üretmeyi bırakır.', null),
  ('Karmaşık görünen çoğu şey, sırayla yapılınca basittir.', null),
  ('Kimseyle değil, geçen haftaki kendinle yarış.', null),
  ('Dinlenmek de işin bir parçasıdır.', null),
  ('Mutluluk, ertelenen şeylerin azaldığı yerdedir.', null),
  ('Bir şeyi anlatamıyorsan, henüz anlamamışsındır.', 'Feynman'),
  ('Az ama düzenli, çok ama arada birden iyidir.', null),
  ('Cesaret, korkmamak değil; korkuya rağmen yapmaktır.', 'Mark Twain'),
  ('Bugün için yeterince iyi olan, mükemmelden iyidir.', null),
  ('Zor olan, doğru olana en yakın duran şeydir çoğu zaman.', null),
  ('Ne ektiğini merak ediyorsan, takvimine bak.', null),
  ('İnsan, dikkatini verdiği şeye dönüşür.', null),
  ('Bitmiş iş, kusursuz plandan iyidir.', null),
  ('Kendine söz verdiğin şeyleri tut; güven oradan başlar.', null),
  ('Her gün biraz; işte bütün sır bu.', null)
on conflict do nothing;
